// <auto-generated />
using MNS.Services.Plan.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MNS.Services.Plan.Migrations
{
    [DbContext(typeof(MobilePlanDbContext))]
    [Migration("20220113125250_MobilePlanDb")]
    partial class MobilePlanDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MNS.Core.Entities.MobilePlan", b =>
                {
                    b.Property<int>("Plan_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CustomerAge")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<int>("ValidityPeriod")
                        .HasMaxLength(365)
                        .HasColumnType("int");

                    b.HasKey("Plan_ID");

                    b.ToTable("MobilePlans");
                });
#pragma warning restore 612, 618
        }
    }
}
