// <auto-generated />
using MNS.Services.Utilization.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MNS.Services.Utilization.Migrations
{
    [DbContext(typeof(UtilizationDbContext))]
    partial class UtilizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MNS.Core.Entities.Utilization", b =>
                {
                    b.Property<int>("Billing_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BillingCycle")
                        .HasColumnType("int");

                    b.Property<int>("Customer_Id")
                        .HasColumnType("int");

                    b.Property<int>("Plan_Id")
                        .HasColumnType("int");

                    b.HasKey("Billing_Id");

                    b.ToTable("Utilizations");
                });
#pragma warning restore 612, 618
        }
    }
}
